# Lesson 1 Practice: NumPy Part 1
Use this notebook to follow along with the lesson in the corresponding lesson notebook: [L01-Numpy_Part1-Lesson.ipynb](./L01-Numpy_Part1-Lesson.ipynb).  



## Instructions
Follow along with the teaching material in the lesson. Throughout the tutorial sections labeled as "Tasks" are interspersed and indicated with the icon: ![Task](http://icons.iconarchive.com/icons/sbstnblnd/plateau/16/Apps-gnome-info-icon.png). You should follow the instructions provided in these sections by performing them in the practice notebook.  When the tutorial is completed you can turn in the final practice notebook. For each task, use the cell below it to write and test your code.  You may add additional cells for any task as needed or desired.  

## Task 1a: Setup

In the practice notebook, import the following packages:
+ `numpy` as `np`

In [1]:
import numpy as np

## Task 2a: Creating Arrays

In the practice notebook, perform the following.  
- Create a 1-dimensional numpy array and print it.
- Create a 2-dimensional numpy array and print it.
- Create a 3-dimensional numpy array and print it.

In [2]:
one_d = np.array([1,2,3])
two_d = np.array([[1,2,3],[1,2,3]])
three_d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[1,2,3]]])

print(one_d)
print(two_d)
print(three_d)

[1 2 3]
[[1 2 3]
 [1 2 3]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [1 2 3]]]


## Task 3a: Accessing Array Attributes

In the practice notebook, perform the following.

- Create a NumPy array.
- Write code that prints these attributes (one per line): `ndim`, `shape`, `size`, `dtype`, `itemsize`, `data`, `nbytes`.
- Add a comment line, before each line describing what value the attribute returns. 


In [3]:
three_d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[1,2,3]]])
# returns 3
print(three_d.ndim)
# returns sides
print(three_d.shape)
# returns number of values inside
print(three_d.size)
# returns 64 bit integer or data type
print(three_d.dtype)
# returns 8
print(three_d.itemsize)
# returns<memory at 0x109cba650>
print(three_d.data)
# returns 96
print(three_d.nbytes)

3
(2, 2, 3)
12
int64
8
96


## Task 4a: Initializing Arrays

In the practice notebook, perform the following.

+ Create an initialized array by using these functions:  `ones`, `zeros`, `empty`, `full`, `arange`, `linspace` and `random.random`. Be sure to follow each array creation with a call to `print()` to display your newly created arrays. 
+ Add a comment above each function call describing what is being done.  

In [4]:
one = np.ones(5)
two = np.zeros(5)
three = np.empty(5)
four = np.full(5, 5)
five = np.arange(0,6)
six = np.linspace(0,6)
seven = 10 * np.random.random_sample((3,3)) - 10

# return a array of 1's with 5 elements, float
print(one)
# returns 5 element array as zero's, float
print(two)
#returns 5 element array as zero's, float
print(three)
# returns 5 element array of fives, integer
print(four)
# returns 6 element array of i+1 increment, integer
print(five)
# returns evenely spaced grid from 1 to 6, float
print(six)
# returns 3 x 3 grid of random numbers ranging from -10, 0
print(seven)

[1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0.]
[4.e-323 0.e+000 0.e+000 0.e+000 0.e+000]
[5 5 5 5 5]
[0 1 2 3 4 5]
[0.         0.12244898 0.24489796 0.36734694 0.48979592 0.6122449
 0.73469388 0.85714286 0.97959184 1.10204082 1.2244898  1.34693878
 1.46938776 1.59183673 1.71428571 1.83673469 1.95918367 2.08163265
 2.20408163 2.32653061 2.44897959 2.57142857 2.69387755 2.81632653
 2.93877551 3.06122449 3.18367347 3.30612245 3.42857143 3.55102041
 3.67346939 3.79591837 3.91836735 4.04081633 4.16326531 4.28571429
 4.40816327 4.53061224 4.65306122 4.7755102  4.89795918 5.02040816
 5.14285714 5.26530612 5.3877551  5.51020408 5.63265306 5.75510204
 5.87755102 6.        ]
[[-9.49882806 -2.7823218  -0.34059194]
 [-1.26664506 -0.39498754 -7.69347262]
 [-3.25143318 -9.95132259 -4.45044179]]


## Task 5a:  Broadcasting Arrays

In the practice notebook, perform the following.

+ Create two arrays of differing sizes but compatible with broadcasting.
+ Perform addition, multiplication and subtraction.
+ Create two additional arrays of differing size that do not meet the rules for broadcasting and try a mathematical operation.  

In [5]:
array_one = np.ones((4,4))
array_two = 5 * np.random.random((4,1,4))
array_three = 10 * np.random.random((7,1,4))
array_four = 5 * np.random.random((10,4))

result_one = array_one + array_two
result_two = array_one - array_two
result_three = array_one * array_two
result_four =  array_three * array_four

print(result_one)
print(result_two)
print(result_three)
print(result_four)

[[[3.66128813 5.9220628  3.76110942 4.41714153]
  [3.66128813 5.9220628  3.76110942 4.41714153]
  [3.66128813 5.9220628  3.76110942 4.41714153]
  [3.66128813 5.9220628  3.76110942 4.41714153]]

 [[4.58264152 3.63378695 5.25510216 2.81720546]
  [4.58264152 3.63378695 5.25510216 2.81720546]
  [4.58264152 3.63378695 5.25510216 2.81720546]
  [4.58264152 3.63378695 5.25510216 2.81720546]]

 [[3.52307155 3.2627178  3.80839771 5.72205553]
  [3.52307155 3.2627178  3.80839771 5.72205553]
  [3.52307155 3.2627178  3.80839771 5.72205553]
  [3.52307155 3.2627178  3.80839771 5.72205553]]

 [[1.69656734 2.85465398 3.64368782 5.56917558]
  [1.69656734 2.85465398 3.64368782 5.56917558]
  [1.69656734 2.85465398 3.64368782 5.56917558]
  [1.69656734 2.85465398 3.64368782 5.56917558]]]
[[[-1.66128813 -3.9220628  -1.76110942 -2.41714153]
  [-1.66128813 -3.9220628  -1.76110942 -2.41714153]
  [-1.66128813 -3.9220628  -1.76110942 -2.41714153]
  [-1.66128813 -3.9220628  -1.76110942 -2.41714153]]

 [[-2.58264152

## Task 6a: Math/Stats Aggregate Functions

In the practice notebook, perform the following.

+ Create three to five arrays
+ Experiment with each of the aggregation functions: `sum`, `minimum`, `maximum`, `cumsum`, `mean`, `np.corrcoef`, `np.std`, `np.var`. 
+ For each function call, add a comment line above it that describes what it does.  
```


In [6]:
df_1 = np.arange(0,6)
df_2 = np.ones((6,6))
df_3 = np.ones((2,6,4))
df_4 = np.random.random((2,6,6))
# returns sum of 0+1+2+3+4+5
print(np.sum(df_1))
# return 4x6x6
print(np.minimum(df_2,df_1))
# returns 12x6
print(np.maximum(df_2, df_4))
# returns the sum of the arrays present
print(np.cumsum(df_3,1))
# returns (0+1+2+3+4+5)/6
print(np.mean(df_1))
# returns correlation of 1 for 1increase in array
print(np.corrcoef(df_1))
# calculates standard deviation of 1x6
print(np.std(df_1))
# returns variance of two identical arrays
print(np.var(df_2))

15
[[0. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1.]]
[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]]
[[[1. 1. 1. 1.]
  [2. 2. 2. 2.]
  [3. 3. 3. 3.]
  [4. 4. 4. 4.]
  [5. 5. 5. 5.]
  [6. 6. 6. 6.]]

 [[1. 1. 1. 1.]
  [2. 2. 2. 2.]
  [3. 3. 3. 3.]
  [4. 4. 4. 4.]
  [5. 5. 5. 5.]
  [6. 6. 6. 6.]]]
2.5
1.0
1.707825127659933
0.0


## Task 6b: Logical Aggregate Functions

In the practice notebook, perform the following.

+ Create two arrays containing boolean values.
+ Experiment with each of the aggregation functions: `logical_and`, `logical_or`, `logical_not`. 
+ For each function call, add a comment line above it that describes what it does.  
```

In [10]:
a = [True, False, True, False]
b = [True, False, True, False]
# returns the boolean expression of if each element of a or b is satisfied 
print(np.logical_or(a,b))
#  Returns the boolean expression if both elements in array a and b is satisfied
print(np.logical_and(a,b))
# returns the compliment expression elements in array
print(np.logical_not(a))

[ True False  True False]
[ True False  True False]
[False  True False  True]
